version: "3.1"

services:
  vite-frontend-prod:
    container_name: vite-frontend-prod
    build:
      context: docker/prod
      dockerfile: Dockerfile
    ports:
      - 5050:80
      - 443:443
    volumes:
      - ./dist:/app
      - ./docker/prod/ngnix/dehydrated:/etc/dehydrated
    restart: always
