version: "3.1"

services:
  frontend:
    user: root
    build:
      context: .
      dockerfile: "docker/${APP_ENV:-development}/Dockerfile"
    container_name: frontend
    entrypoint: "./entrypoint.sh"
    restart: always
    ports:
      - "${APP_PORT:-5050}:5050"
    env_file: .env
    volumes:
      - ./src:/home/appuser/app/src
      - ./dist:/home/appuser/app/dist
      - ./node_modules:/home/appuser/app/node_modules
      - ./package.json:/home/appuser/app/package.json
      - ./package-lock.json:/home/appuser/app/package-lock.json
